### ISSUE TITLE
build error if the text contain `/*` in vite3.0

### ISSUE THREAD

**Issue by hans000** [chengpeiquan/vite-plugin-banner#13]
i need `/*` in text, a very useful scenario is when developing tampermonkey script.

```
const prefix = `
// @match           https://www.foo.com/*
// @match           https://*/*
`

>>> error msg
Error: [vite-plugin-banner] If you want to pass in comment symbols, you must pass them in pairs.
```

perharps, it needs a option to keep raw text and manual comment by user or handle escape `/*`

**Comment by douglasg14b** [comment]
The above link is dead, where did that go?

**Comment by chengpeiquan** [comment]
> The above link is dead, where did that go?

Hi, the latest code is here 
https://github.com/chengpeiquan/vite-plugin-banner/blob/v0.8.0/src/types.ts#L32-L43
(I am now pointing to the latest Tag to ensure that the link does not become invalid.)
