### ISSUE TITLE
Disable automatic comments

### ISSUE THREAD

**Issue by gius** [chengpeiquan/vite-plugin-banner#24]
Can I disable the `/*! ... */` wrapper? I would like to use this plugin to inject a `#!/usr/bin/env node` shebang to the code.

**Comment by chengpeiquan** [comment]
Of course, the content is highly customizable. Comment symbols will only be added when they are missing. 
Refer to this example:  [vite.config.ts](https://github.com/awesome-starter/create-preset/blob/main/vite.config.ts#L31)

**Comment by gius** [comment]
Ah, good point - I actually have to add any comment to skip the automatic wrapping.

I mean, this does not work:
```
  plugins: [
    banner(
      `#!/usr/bin/env node`
    ),
  ],
```

whereas this works:
```
  plugins: [
    banner(
      `#!/usr/bin/env node\n/* My app */`
    ),
  ],
```

**Comment by chengpeiquan** [comment]
Please upgrade to `0.7.0` and set the `verify` option to `false`:

```ts
// vite.config.ts
export default defineConfig({
  plugins: [
    banner({
      content: `#!/usr/bin/env node`,
      verify: false,
    }),
  ],
})
```
