### ISSUE TITLE
`outDir` unable to inherit vite configuration

### ISSUE THREAD

**Issue by hooray** [chengpeiquan/vite-plugin-banner#29]
```js
// vite.config.ts

export default defineConfig({
  build: {
    outDir: 'dist-example'
  },
  plugins: [
    banner('/* test */'),
  ],
})
```

I think if the plugin doesn't have `outDir` set, it should default to vite's `outDir` configuration, but the actual result is that the plugin `ourDir` defaults to `dist` all the time, and the reason for that is because it's being forced to format to the default value of `dist` in `src/libs/formatConfig.ts`

https://github.com/chengpeiquan/vite-plugin-banner/blob/312dec8adbb70e64dd8d5247a0f2e67f8c16a5b6/src/libs/formatConfig.ts#L19

Causes this `||` code in `src/main.ts` to be redundant

https://github.com/chengpeiquan/vite-plugin-banner/blob/312dec8adbb70e64dd8d5247a0f2e67f8c16a5b6/src/main.ts#L47-L48

BTW, is the `outDir` config item really needed, it makes more sense to always use vite's `outDir`, right?

**Comment by chengpeiquan** [comment]
The plugin's outDir is optional and was previously inherited, so it only needed to be specified when necessary.

I ran the latest vite demo and reproduced this problem. It should be that the configuration was not inherited after a certain version of Vite was upgraded.
